---

- name: Copy rsyslog configuration file
  template:
    src: "{{ item }}.j2"
    dest: "/etc/rsyslog.d/{{item}}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - graylog.conf
  notify:
    - restart rsyslog service
