---

- name: Create admin group
  group:
    name: "{{ admin_group }}"
    state: present

- name: Setup all admin users
  user:
    name: "{{ item.username }}"
    state: "{{ item.state | default('present') }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    group: "{{ admin_group }}"
    remove: yes
  when: item.username is defined
  with_items:
    - "{{ admin_list }}"

- name: Add SSH-keys to admin users
  authorized_key:
    user: "{{ item.0.username }}"
    key: "{{ item.1 }}"
  with_subelements:
    - "{{ admin_list }}"
    - keys.active
    - flags:
      skip_missing: yes
  when: item.0.state != "absent"

- name: Remove old SSH-keys from admin users
  authorized_key:
    user: "{{ item.0.username }}"
    key: "{{ item.1 }}"
    state: absent
  with_subelements:
    - "{{ admin_list }}"
    - keys.disabled
    - flags:
      skip_missing: yes
  when: item.0.state != "absent"

- name: Add admin group to sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%{{ admin_group }}"
    line: "%{{ admin_group }} ALL=(ALL) NOPASSWD:ALL"

- name: Disable Requiretty from sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: "Defaults requiretty"
    line: "#Defaults requiretty"
